name: mishka app unit test

on:
  push:
    pull_request:
      branches:
        - master

env:
  FLUTTER_VERSION: "2.10.2"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VERSION
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test